FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY src/scanner/go.mod src/scanner/go.sum ./
RUN go mod download

COPY src/scanner/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o /scanner main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /scanner /usr/local/bin/scanner

EXPOSE 8001

CMD ["scanner", "serve"]
